In [3]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from xgboost import XGBRegressor
import joblib 
import numpy as np

In [4]:
df = pd.read_csv("medical_insurance.csv")
df.head()

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,75722,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,...,0,1,0,1,0,2,0,1,0,0
1,80185,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,...,0,1,1,0,0,1,0,1,1,0
2,19865,68,Male,North,Rural,40700.0,HS,Married,Retired,5,...,0,0,1,1,0,2,1,0,1,0
3,76700,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,...,0,0,0,1,0,0,1,0,0,0
4,92992,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,...,0,1,0,2,0,1,1,0,1,0

In [5]:
df.columns

Index(['person_id', 'age', 'sex', 'region', 'urban_rural', 'income',
       'education', 'marital_status', 'employment_status', 'household_size',
       'dependents', 'bmi', 'smoker', 'alcohol_freq', 'visits_last_year',
       'hospitalizations_last_3yrs', 'days_hospitalized_last_3yrs',
       'medication_count', 'systolic_bp', 'diastolic_bp', 'ldl', 'hba1c',
       'plan_type', 'network_tier', 'deductible', 'copay', 'policy_term_years',
       'policy_changes_last_2yrs', 'provider_quality', 'risk_score',
       'annual_medical_cost', 'annual_premium', 'monthly_premium',
       'claims_count', 'avg_claim_amount', 'total_claims_paid',
       'chronic_count', 'hypertension', 'diabetes', 'asthma', 'copd',
       'cardiovascular_disease', 'cancer_history', 'kidney_disease',
       'liver_disease', 'arthritis', 'mental_health', 'proc_imaging_count',
       'proc_surgery_count', 'proc_physio_count', 'proc_consult_count',
       'proc_lab_count', 'is_high_risk', 'had_major_procedure'],
      dtype='str')

In [6]:
df.dtypes

person_id                        int64
age                              int64
sex                                str
region                             str
urban_rural                        str
income                         float64
education                          str
marital_status                     str
employment_status                  str
household_size                   int64
dependents                       int64
bmi                            float64
smoker                             str
alcohol_freq                       str
visits_last_year                 int64
hospitalizations_last_3yrs       int64
days_hospitalized_last_3yrs      int64
medication_count                 int64
systolic_bp                    float64
diastolic_bp                   float64
ldl                            float64
hba1c                          float64
plan_type                          str
network_tier                       str
deductible                       int64
copay                            int64
policy_term_years                int64
policy_changes_last_2yrs         int64
provider_quality               float64
risk_score                     float64
annual_medical_cost            float64
annual_premium                 float64
monthly_premium                float64
claims_count                     int64
avg_claim_amount               float64
total_claims_paid              float64
chronic_count                    int64
hypertension                     int64
diabetes                         int64
asthma                           int64
copd                             int64
cardiovascular_disease           int64
cancer_history                   int64
kidney_disease                   int64
liver_disease                    int64
arthritis                        int64
mental_health                    int64
proc_imaging_count               int64
proc_surgery_count               int64
proc_physio_count                int64
proc_consult_count               int64
proc_lab_count                   int64
is_high_risk                     int64
had_major_procedure              int64
dtype: object

In [7]:
df.isnull().sum()

person_id                          0
age                                0
sex                                0
region                             0
urban_rural                        0
income                             0
education                          0
marital_status                     0
employment_status                  0
household_size                     0
dependents                         0
bmi                                0
smoker                             0
alcohol_freq                   30083
visits_last_year                   0
hospitalizations_last_3yrs         0
days_hospitalized_last_3yrs        0
medication_count                   0
systolic_bp                        0
diastolic_bp                       0
ldl                                0
hba1c                              0
plan_type                          0
network_tier                       0
deductible                         0
copay                              0
policy_term_years                  0
policy_changes_last_2yrs           0
provider_quality                   0
risk_score                         0
annual_medical_cost                0
annual_premium                     0
monthly_premium                    0
claims_count                       0
avg_claim_amount                   0
total_claims_paid                  0
chronic_count                      0
hypertension                       0
diabetes                           0
asthma                             0
copd                               0
cardiovascular_disease             0
cancer_history                     0
kidney_disease                     0
liver_disease                      0
arthritis                          0
mental_health                      0
proc_imaging_count                 0
proc_surgery_count                 0
proc_physio_count                  0
proc_consult_count                 0
proc_lab_count                     0
is_high_risk                       0
had_major_procedure                0
dtype: int64

In [9]:
df.head()

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,75722,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,...,0,1,0,1,0,2,0,1,0,0
1,80185,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,...,0,1,1,0,0,1,0,1,1,0
2,19865,68,Male,North,Rural,40700.0,HS,Married,Retired,5,...,0,0,1,1,0,2,1,0,1,0
3,76700,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,...,0,0,0,1,0,0,1,0,0,0
4,92992,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,...,0,1,0,2,0,1,1,0,1,0

In [13]:
df["alcohol_freq"].nunique()

3

In [18]:
df["alcohol_freq"].fillna(df["alcohol_freq"].mode()[0])

0        Occasional
1            Weekly
2        Occasional
3        Occasional
4             Daily
            ...
99995    Occasional
99996    Occasional
99997        Weekly
99998    Occasional
99999    Occasional
Name: alcohol_freq, Length: 100000, dtype: str